### ISSUE TITLE
parameters option seems to be ignored

### ISSUE THREAD

**Issue by avishnyakov** [wildbillcat-cookbooks/webdeploymenttoolkit#10]
Hello, 

Using webdeploymenttoolkit to get webdeploy package pushed. Somehow, parameters option is ignored with the following config:

```rb
web_deploy 'package=c:\vagrant\_tmp_app.zip' do
  dest 'auto'
  parameters = {
    'IIS Web Application Name' => 'Default Web Site/app',
    'connectionString' => 'tada'
  }
  action :sync
end
```
The output always looks as following:
```
 - execute "%programfiles%\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package=c:\vagrant\_tmp_app.zip' -dest:auto
```
Checked the source code for the provider, clearly see the loop over parameters option, yet the console output still the same.

Overlooking something?

**Comment by avishnyakov** [comment]
My bad, all good. Here is updated version:

``` rb
web_deploy 'package=c:\vagrant\_tmp_app.zip' do
  dest 'auto'
  action :sync
  parameters ({
      'IIS Web Application Name' => 'Default Web Site/app',
      'DefaultConnection-Web.config Connection String' => 'tada'
  })
end
```

**Comment by wildbillcat** [comment]
Sorry for the delay! Glad you got it. :)

**Comment by wildbillcat** [comment]
Oh and I updated the readme documentation, my apologies for the oversight!

**Comment by avishnyakov** [comment]
Cool, no worries. That's my lack of Ruby, I guess. Fixable :)

Thanks for the package. Not only useful but also shows how one can create a new package to wrap up some EXE-like tooling.
