### ISSUE TITLE
Url 'https://www.microsoft.com/en-us/web/webpi/4.6/webproductlist.xml' returned HTTP status code: 404

### ISSUE THREAD

**Issue by mmclane** [wildbillcat-cookbooks/webdeploymenttoolkit#12]
1517935130,,ui,message,    amazon-ebs: [2018-02-06T11:38:49-05:00] INFO: Processing webpi_product[WDeployNoSMO] action install (webdeploymenttoolkit::default line 8)
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: ================================================================================
1517935136,,ui,message,    amazon-ebs: Error executing action `install` on resource 'webpi_product[WDeployNoSMO]'
1517935136,,ui,message,    amazon-ebs: ================================================================================
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed
1517935136,,ui,message,    amazon-ebs: ------------------------------------
1517935136,,ui,message,    amazon-ebs: Expected process to exit with [0%!(PACKER_COMMA) 42]%!(PACKER_COMMA) but received '-1'
1517935136,,ui,message,    amazon-ebs: ---- Begin output of "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log ----
1517935136,,ui,message,    amazon-ebs: STDOUT: The software that you obtain using the Web Plaform Installer Command Line Tool is licensed to you by its owner.  Microsoft grants you no rights for third party software.
1517935136,,ui,message,    amazon-ebs: .  \r .. \r ...\r    \r    \rUnexpected exception occurred
1517935136,,ui,message,    amazon-ebs: Url 'https://www.microsoft.com/en-us/web/webpi/4.6/webproductlist.xml' returned HTTP status code: 404
1517935136,,ui,message,    amazon-ebs: STDERR:
1517935136,,ui,message,    amazon-ebs: ---- End output of "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log ----
1517935136,,ui,message,    amazon-ebs: Ran "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log returned -1
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: Resource Declaration:
1517935136,,ui,message,    amazon-ebs: ---------------------
1517935136,,ui,message,    amazon-ebs: # In c:/chef/cache/cookbooks/webdeploymenttoolkit/recipes/default.rb
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: 8: webpi_product 'WDeployNoSMO' do
1517935136,,ui,message,    amazon-ebs: 9:   accept_eula true
1517935136,,ui,message,    amazon-ebs: 10:   action :install
1517935136,,ui,message,    amazon-ebs: 11: end
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: Compiled Resource:
1517935136,,ui,message,    amazon-ebs: ------------------
1517935136,,ui,message,    amazon-ebs: # Declared in c:/chef/cache/cookbooks/webdeploymenttoolkit/recipes/default.rb:8:in `from_file'
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: webpi_product("WDeployNoSMO") do
1517935136,,ui,message,    amazon-ebs: action [:install]
1517935136,,ui,message,    amazon-ebs: retries 0
1517935136,,ui,message,    amazon-ebs: retry_delay 2
1517935136,,ui,message,    amazon-ebs: default_guard_interpreter :default
1517935136,,ui,message,    amazon-ebs: declared_type :webpi_product
1517935136,,ui,message,    amazon-ebs: cookbook_name "webdeploymenttoolkit"
1517935136,,ui,message,    amazon-ebs: recipe_name "default"
1517935136,,ui,message,    amazon-ebs: accept_eula true
1517935136,,ui,message,    amazon-ebs: product_id "WDeployNoSMO"
1517935136,,ui,message,    amazon-ebs: end
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: Platform:
1517935136,,ui,message,    amazon-ebs: ---------
1517935136,,ui,message,    amazon-ebs: x64-mingw32
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: [2018-02-06T11:38:56-05:00] INFO: Running queued delayed notifications before re-raising exception
1517935136,,ui,message,    amazon-ebs: [2018-02-06T11:38:56-05:00] ERROR: Running exception handlers
1517935136,,ui,message,    amazon-ebs: [2018-02-06T11:38:56-05:00] ERROR: Exception handlers complete
1517935136,,ui,message,    amazon-ebs: [2018-02-06T11:38:56-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
1517935136,,ui,message,    amazon-ebs: [2018-02-06T11:38:56-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
1517935136,,ui,message,    amazon-ebs: [2018-02-06T11:38:56-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: webpi_product[WDeployNoSMO] (webdeploymenttoolkit::default line 8) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0%!(PACKER_COMMA) 42]%!(PACKER_COMMA) but received '-1'
1517935136,,ui,message,    amazon-ebs: ---- Begin output of "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log ----
1517935136,,ui,message,    amazon-ebs: STDOUT: The software that you obtain using the Web Plaform Installer Command Line Tool is licensed to you by its owner.  Microsoft grants you no rights for third party software.
1517935136,,ui,message,    amazon-ebs: .  \r .. \r ...\r    \r    \rUnexpected exception occurred
1517935136,,ui,message,    amazon-ebs: Url 'https://www.microsoft.com/en-us/web/webpi/4.6/webproductlist.xml' returned HTTP status code: 404
1517935136,,ui,message,    amazon-ebs: STDERR:
1517935136,,ui,message,    amazon-ebs: ---- End output of "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log ----
1517935136,,ui,message,    amazon-ebs: Ran "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log returned -1
1517935136,,ui,message,    amazon-ebs: Creating configuration file 'knife.rb'
1517935137,,ui,say,==> amazon-ebs: Cleaning up chef node...
1517935141,,ui,message,    amazon-ebs: Deleted node[packer-5a79d8b8-bf7e-0232-a9ef-62a4cf65a81f]
1517935141,,ui,error,==> amazon-ebs: Step "StepProvision" failed%!(PACKER_COMMA) aborting...
1517935141,,ui,error,Build 'amazon-ebs' errored: unexpected EOF
1517935141,,error-count,1

**Comment by wildbillcat** [comment]
Hi there, @iennae swept in and appears to have resolved this issue, I pushed it up onto the supermarket. Let me know if you run into any problems.
