### ISSUE TITLE
No provider found

### ISSUE THREAD

**Issue by olivierlemasle** [wildbillcat-cookbooks/webdeploymenttoolkit#4]
Hi,

Thanks for this cookbook!

Actually, I started using this cookbook yesterday, when it was in version 0.1.2.

In order to use the web_deploy resource in my cookbook, I had to call it  `webdeploymenttoolkit_web_deploy`.

In commit 1e4f373fe6 (version 0.1.4), you added the `:resource_name`, so I can call your resource `web_deploy`. But the provider is now not resolved. Here is the error I get:

```
  Chef::Exceptions::ProviderNotFound
  ----------------------------------
  Cannot find a provider for web_deploy[package=C:/chef/cache/WebApp.zip] on windows version 6.1.7601
```

I reverted to version 0.1.2 and I have no issue... Do you know if I have to configure the provider manually?

**Comment by olivierlemasle** [comment]
Thanks, it works since version 0.1.7.

**Comment by wildbillcat** [comment]
Sorry about that! I was fiddling to get it up to spec for Chef 13, since I originally made it following an old Chef Spec. Sorry for the trouble, I'll avoid being so haphazard with my revisions in the future! :)
