### ISSUE TITLE
Feature Request for SetParmeter

### ISSUE THREAD

**Issue by HaroonSaid** [wildbillcat-cookbooks/webdeploymenttoolkit#9]
We would like the ability to pass match string instead of name for Set Parameter
e.g. 
  @new_resource.match.each do |name, value|
    msdeploy_cmd << "-setParam:match=\"#{name}\",value=\"#{value}\" "
  end unless @new_resource.match.nil?

**Comment by wildbillcat** [comment]
Thats a good point, I was a little short sighted when I added the feature. Support for kind and scope would also be nice, I'll sleep on it and see if I can take this up tomorrow.
